deployment:
- any: ['.github/workflows/*.yml', '!labeler.yml']

project:
- '*.sln'
- '*.proj'

design:
- 'src/Resources/*.png'
- 'src/Resources/*.jpg'
- 'src/Resources/*.mp*'
- 'src/Resources/*.m4*'
- 'src/Resources/*.wav'

documentation:
- '*.md'
- '*.pdf'
- '*.html'


backend:
- 'src/*VCard*.cs'
- 'src/*Engine*.cs'
- 'src/*Field*.cs'

frontend:
- 'src/*Form*.cs'
- 'src/*Form*.resx'
- 'src/*Element*.cs'
- 'src/*Element*.resx'

testcase:
- './**/*Test*.cs'
