deployment:
- any: ['.github/workflows/*.yml', '!labeler.yml']

project:
- '*.sln'
- '*.proj'

design:
- 'src/Resources/*.png'

backend:
- './**/*VCard*.cs'
- './**/*Engine*.cs'
- './**/*Field*.cs'

frontend:
- './**/*Form*.cs'
- './**/*Form*.resx'
- './**/*Element*.cs'
- './**/*Element*.resx'

testcase:
- './**/*Test*.cs'
