deployment:
- any: ['.github/workflows/*.yml', '!labeler.yml']

project:
- '*.sln'
- '*.proj'

design:
- 'src/Resources/*.png'
- 'src/Resources/*.jpg'
- 'src/Resources/*.mp*'
- 'src/Resources/*.m4*'
- 'src/Resources/*.wav'

documentation:
- '*.md'
- '*.pdf'
- '*.html'


backend:
- './**/*VCard*.cs'
- './**/*Engine*.cs'
- './**/*Field*.cs'

frontend:
- './**/*Form*.cs'
- './**/*Form*.resx'
- './**/*Element*.cs'
- './**/*Element*.resx'

testcase:
- './**/*Test*.cs'
